### ISSUE TITLE
colors gets wrong as soon as I unfocus

### ISSUE THREAD

**Issue by romaintb** [joerx/base16-terminator#1]
Hi,

might not be related to this config, but my colors gets wrong as soon as I unfocus terminator (I can see it in vim, or even the cursor in the shell gets black instead of white).
Did you have a similar problem ? If so how did you managed to fix that ?

Thansk a lot.

**Comment by joerx** [comment]
Sorry, can't reproduce the problem. Using terminator 0.97 on Xubuntu 12.04. Full config below:

```
[global_config]
  title_transmit_bg_color = "#0055c8"
  suppress_multiple_term_dialog = True
[keybindings]
  switch_to_tab_10 = <Alt>0
  switch_to_tab_4 = <Alt>4
  switch_to_tab_5 = <Alt>5
  switch_to_tab_2 = <Alt>2
  switch_to_tab_3 = <Alt>3
  switch_to_tab_1 = <Alt>1
[profiles]
  [[default]]
    scrollbar_position = hidden
    use_system_font = False
    font = Source Code Pro Medium 10
    background_image = None
[layouts]
  [[default]]
    [[[child1]]]
      type = Terminal
      parent = window0
    [[[window0]]]
      type = Window
      parent = ""
[plugins]
```

**Comment by shrx** [comment]
I have the same problem with the Solarized dark theme, so the issue seems to be something else.

edit: https://bugs.launchpad.net/terminator/+bug/1177506
the temporary fix is to set Unfocused terminal font brightness to 0.9.

**Comment by romaintb** [comment]
Alright, thanks for the hint @shrx, and thanks for taking a look @joerx :)
